type ContentBlock =
  | {
      type: 'paragraph';
      text: string;
    }
  | {
      type: 'list';
      items: string[];
      ordered?: boolean;
    }
  | {
      type: 'subheading';
      text: string;
    };

type PrivacySection = {
  id: string;
  title: string;
  blocks: ContentBlock[];
};

const sections: PrivacySection[] = [
  {
    id: 'general',
    title: '1. General',
    blocks: [
      {
        type: 'paragraph',
        text: 'This document is an electronic record in terms of the Information Technology Act, 2000 and the applicable rules thereunder, including amended provisions relating to electronic records in various statutes. This electronic record is generated by a computer system and does not require physical or digital signatures.',
      },
      {
        type: 'paragraph',
        text: 'This Privacy Policy is published in accordance with applicable Indian law and is intended to explain how Tax Suvidha Kendra and TaxSuvidhaKendra.com collect, use, store, disclose and protect information provided by users of the website and related services.',
      },
      {
        type: 'paragraph',
        text: 'For the purpose of this Privacy Policy, the terms you and user mean any person or entity accessing or using the website or services. The terms we, us and our mean Tax Suvidha Kendra, the website TaxSuvidhaKendra.com and the persons operating it, as the context requires.',
      },
      {
        type: 'paragraph',
        text: 'The headings in this Policy are for convenience only and do not affect interpretation. Your use of the website is governed by this Policy together with the Terms and Conditions and any other applicable service-specific terms published on the website.',
      },
      {
        type: 'paragraph',
        text: 'By visiting the website, submitting forms, purchasing services, requesting consultations, uploading documents or otherwise using our services, you acknowledge that you have read, understood and agreed to this Privacy Policy. We reserve the right to amend this Policy at any time, and continued use of the website after updates constitutes acceptance of the revised Policy.',
      },
    ],
  },
  {
    id: 'collection',
    title: '2. Collection of Personal and Other Information',
    blocks: [
      {
        type: 'paragraph',
        text: 'We may collect and store personal information that you provide directly to us through enquiry forms, consultation forms, service requests, account registration, communications, uploads and other interactions on the website. This may include your name, phone number, email address, postal address, business details, tax or compliance related information, identification information, uploaded documents and any other information you choose to provide.',
      },
      {
        type: 'paragraph',
        text: 'We may also automatically collect certain technical and usage information, including your IP address, browser type, device details, operating system, approximate location, referring URL, pages visited, timestamps and interactions with the website. This information helps us understand user behavior, improve performance, troubleshoot issues and maintain security.',
      },
      {
        type: 'paragraph',
        text: 'If you purchase or request services from us, we may collect information related to transaction history, service preferences, order details, payment status, invoice details and communications necessary to deliver and support the requested service. Payment card or banking information may be processed by authorized payment service providers rather than stored directly by us, except to the limited extent necessary for billing records, reconciliation, refund processing or compliance.',
      },
      {
        type: 'paragraph',
        text: 'If you provide a mobile number, email address or other contact details, you consent to receiving communications from us regarding your enquiry, service request, account activity, reminders, follow-ups, support responses, offers, updates and promotional messages, subject to applicable law. Where required to fulfill services or send communications, we may share relevant contact information with authorized service providers, partners or professionals assisting with your request.',
      },
      {
        type: 'paragraph',
        text: 'If you post reviews, feedback, testimonials, comments or other content on the website, that information may be stored, displayed and used by us to improve services, resolve disputes, support customers, investigate complaints and comply with legal obligations. We reserve the right to remove such content at our discretion.',
      },
      {
        type: 'paragraph',
        text: 'Some parts of the website may be accessible without registration, but certain services require you to provide accurate personal information. If you choose not to provide required information, we may be unable to offer the requested service or support.',
      },
      {
        type: 'paragraph',
        text: 'We may occasionally request optional survey responses, feedback or reviews to better understand user needs, improve content, personalize user experience and refine our services. Submission of optional information is voluntary, but if provided it may be retained and used in accordance with this Policy.',
      },
      {
        type: 'list',
        items: [
          'Identity and contact data such as name, email address, phone number and address',
          'Business, tax, compliance and document-related information you submit to obtain services',
          'Technical and device data such as IP address, browser, operating system and usage patterns',
          'Transaction, billing and payment-related records necessary for service fulfillment or refunds',
          'Communications, support messages, uploaded files, survey responses and user feedback',
        ],
      },
    ],
  },
  {
    id: 'cookies',
    title: '3. Cookies',
    blocks: [
      {
        type: 'paragraph',
        text: 'A cookie is a small piece of information stored by your browser that allows a website to recognize your device or retain certain preferences. Tax Suvidha Kendra may use cookies and similar technologies to maintain sessions, improve usability, remember preferences, analyze traffic, understand engagement and help maintain trust and security on the website.',
      },
      {
        type: 'paragraph',
        text: 'You may refuse or disable cookies through your browser settings, but doing so may limit the functionality or availability of some features on the website. Third-party services used on the website may also place cookies or similar technologies, and we do not control the operation of such third-party tools beyond our own implementation choices.',
      },
    ],
  },
  {
    id: 'sharing',
    title: '4. Divulging or Sharing of Personal Information',
    blocks: [
      {
        type: 'paragraph',
        text: 'We may share your personal information with affiliates, employees, consultants, service providers, payment processors, hosting providers, communication vendors, compliance professionals, advisors and other authorized third parties to the extent reasonably necessary to operate the website, provide requested services, process payments, prevent fraud, improve user experience, resolve complaints and comply with legal obligations.',
      },
      {
        type: 'paragraph',
        text: 'We may disclose personal information if required by law, regulation, court order, lawful governmental request or legal process, or if we believe in good faith that such disclosure is necessary to enforce our terms, investigate misuse, respond to claims, protect our rights, or protect the rights, property or safety of users, service providers or the public.',
      },
      {
        type: 'paragraph',
        text: 'In the event of a merger, acquisition, business transfer, restructuring, reorganization or sale of assets, user information may be transferred as part of that transaction, subject to applicable confidentiality and data protection obligations.',
      },
    ],
  },
  {
    id: 'security',
    title: '5. Security',
    blocks: [
      {
        type: 'paragraph',
        text: 'We use reasonable administrative, technical and organizational safeguards to protect personal information against unauthorized access, misuse, alteration, disclosure or destruction. Information submitted through the website may be protected through access controls, encryption in transit, hosting safeguards and operational security practices appropriate to the nature of the data and services.',
      },
      {
        type: 'paragraph',
        text: 'Despite our efforts, no method of transmission over the internet or method of electronic storage is completely secure. Accordingly, we cannot guarantee absolute security and you provide information at your own risk. Users should exercise caution while submitting sensitive information online.',
      },
    ],
  },
  {
    id: 'third-party',
    title: '6. Third Party Links, Advertisements and Promotions',
    blocks: [
      {
        type: 'paragraph',
        text: 'The website may contain links to third-party websites, embedded tools, service providers, advertisements or partner content. Such third parties may collect information independently under their own privacy policies. Tax Suvidha Kendra is not responsible for the privacy practices, terms, content or security standards of third-party websites or services and users should review those policies independently before interacting with them.',
      },
    ],
  },
  {
    id: 'consent',
    title: '7. User Consent',
    blocks: [
      {
        type: 'paragraph',
        text: 'By using the website or providing information through the website, you consent to the collection, storage, use and disclosure of information as described in this Privacy Policy. Where you provide another person information or documents, you represent that you are authorized to do so and to permit us to process that information for the relevant service or purpose.',
      },
    ],
  },
  {
    id: 'retention',
    title: '8. Data Retention',
    blocks: [
      {
        type: 'paragraph',
        text: 'We retain personal information only for as long as reasonably necessary for the purposes for which it was collected, including service fulfillment, follow-up support, legal compliance, accounting, dispute resolution, internal record-keeping, fraud prevention and enforcement of our agreements. Retention periods may vary depending on the nature of the information and applicable legal requirements.',
      },
    ],
  },
  {
    id: 'grievance',
    title: '9. Grievance Officer and Contact',
    blocks: [
      {
        type: 'paragraph',
        text: 'If you have any questions, complaints, notices or concerns relating to privacy, data handling or this Policy, you may contact us using the details below:',
      },
      {
        type: 'list',
        items: [
          'Email: info@taxsuvidhakendra.com',
          'Phone: +91 9999 24 1024',
          'Address: Office Number 403, Jain Complex, Opposite Metroplex Mall, Nirman Vihar, Delhi 110092',
          'Website: https://taxsuvidha-c3c4a.web.app',
        ],
      },
    ],
  },
  {
    id: 'dispute',
    title: '10. Dispute Resolution and Jurisdiction',
    blocks: [
      {
        type: 'paragraph',
        text: 'The formation, interpretation and performance of this Privacy Policy and any disputes arising from it shall be governed by the laws of India. The parties shall first attempt to resolve disputes amicably. If a dispute cannot be resolved through discussion, it may be referred to arbitration in accordance with applicable Indian law. Subject to applicable law, the courts at Delhi shall have jurisdiction over disputes arising out of or related to this Policy and the use of the website.',
      },
    ],
  },
];

export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen bg-white dark:bg-black">
      <section className="border-b border-gray-200 bg-gray-50 py-20 dark:border-gray-700 dark:bg-gray-900">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-bold text-gray-900 sm:text-5xl dark:text-white">
            Privacy Policy
          </h1>
          <p className="mt-4 text-sm text-gray-600 dark:text-gray-400">
            Last updated: March 20, 2026
          </p>
        </div>
      </section>

      <section className="py-10 sm:py-12">
        <div className="mx-auto max-w-5xl space-y-10 px-4 sm:px-6 lg:px-8">
          {sections.map((section) => (
            <div key={section.id}>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
                {section.title}
              </h2>

              <div className="mt-4 space-y-4 text-gray-600 dark:text-gray-400">
                {section.blocks.map((block, index) => {
                  if (block.type === 'paragraph') {
                    return <p key={`${section.id}-${index}`}>{block.text}</p>;
                  }

                  if (block.type === 'subheading') {
                    return (
                      <h3
                        key={`${section.id}-${index}`}
                        className="pt-2 text-lg font-semibold text-gray-900 dark:text-white"
                      >
                        {block.text}
                      </h3>
                    );
                  }

                  const ListTag = block.ordered ? 'ol' : 'ul';
                  const listClassName = block.ordered
                    ? 'list-decimal space-y-2 pl-6'
                    : 'list-disc space-y-2 pl-6';

                  return (
                    <ListTag key={`${section.id}-${index}`} className={listClassName}>
                      {block.items.map((item) => (
                        <li key={item}>{item}</li>
                      ))}
                    </ListTag>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </section>
    </main>
  );
}
